### PR TITLE
xapi_xenops: Avoid a race during suspend

### LINKED ISSUE #6451: Race condition in `xapi_xenops` overwriting VM data on suspend makes it unresumable
We've been seeing a particularly nasty error at Vates, with symptoms like:

```
$ xe vm-resume uuid=XXX
xenopsd internal error: File "ocaml/xenopsd/xc/domain.ml", 
line 1585, characters 2-8: Assertion failed
```

The assertion is this in `restore`:
```
let restore (task : Xenops_task.task_handle) ~xc ~xs ~dm ~store_domid
    ~console_domid ~no_incr_generationid ~timeoffset ~extras info ~manager_path
    ~vtpm domid fd vgpu_fd =
  let static_max_kib = info.memory_max in
  let target_kib = info.memory_target in
 ...
  assert (target_mib <= static_max_mib) ;
```

(We do not have any patches against any of the code involved, nor have I found anything that'd make this less likely on master - I'm testing on 25.6.0)

Suspending and resuming a VM on a supporter host makes this a lot more likely to occur (but doesn't always occur even there).

I've boiled the cause down to this:

On a good attempt, the sequence is as follows:
```
09:55:26 xenopsd-xc: [debug||32 |Async.VM.suspend|xenops] 
Final memory usage of the domain = 1049083 pages

09:55:27 xenopsd-xc: [debug||32 |Async.VM.suspend|xenops] 
Storing final memory usage, suspend_memory_bytes: 4297043968

09:55:35 xapi: [debug||103 |org.xen.xapi.xenops.classic events|xenops] 
Will update VM.allowed_operations because power_state has changed.
09:55:35 xapi: [debug||103 |org.xen.xapi.xenops.classic events|xenops] 
xenopsd event: Updating VM XXX power_state <- Suspended

< not interrupted by anything >

09:55:36 xapi: [ info||103 |org.xen.xapi.xenops.classic events|xenops]
xenops: VM.export_metadata 
09:55:37 xapi: [debug||103 |org.xen.xapi.xenops.classic events|xenops] 
 last_booted_record set to "suspend_memory_bytes":4297043968, 
                                                "memory_target":4194304,
                                                "memory_max":4194304 <--- right numbers

all of data sent after has right suspend_memory_bytes, e.g.:
09:55:39 xapi: [debug||17 HTTPS 2a01:240:ab08:5:15::23->:::80|Async.VM.resume|xenops] 
Sending VM XXX configuration to xenopsd
09:55:39 xapi: [ info||17 HTTPS 2a01:240:ab08:5:15::23->:::80|Async.VM.resume|xenops] 
xenops: VM.import_metadata "suspend_memory_bytes\\":4297043968 <--- right numbers
```

A bad sequence looks like this:
```
10:46:36 xenopsd-xc: [debug||40 |Async.VM.suspend|xenops] 
Storing final memory usage, suspend_memory_bytes: 4297043968

10:46:40 xapi: [debug||101 |org.xen.xapi.xenops.classic events|xenops] 
Will update VM.allowed_operations because power_state has changed.
10:46:40 xapi: [debug||101 |org.xen.xapi.xenops.classic events|xenops] 
xenopsd event: Updating VM XXX power_state <- Suspended

< interrupted by event that overwrites data >
10:46:41 xapi: [debug||103 |xapi events|xenops] 
VM XXX metadata has changed: updating xenopsd
10:46:41 xapi: [ info||103 |xapi events|xenops] 
xenops: VM.import_metadata "suspend_memory_bytes\\":2149568512 <-- wrong number
<>

10:46:42 xapi: [ info||101 |org.xen.xapi.xenops.classic events|xenops]
xenops: VM.export_metadata 
10:46:42 - last_booted_record set to wrong numbers now

xenopsd on restore picks up wrong numbers and raises the assert, rightfully.
10:46:48 xenopsd-xc: [ warn||18 |Async.VM.resume|xenops]
static_max_kib: 2097152, target_kib: 2099188, static_max_mib: 2048, target_mib: 2050
```

I'm looking into how this could be fixed, but posting it here as a warning - maybe someone already knows this is an issue?

### PR DESCRIPTION
**Pull request by last-genius**
As described in [#6451](https://github.com/xapi-project/xen-api/issues/6451), a xapi event could prevent update_vm from pulling the latest Xenopsd metadata, overwriting it with stale information. In case of suspend, this would make the snapshot unresumable, raising an assert in xenopsd due to incongruities in memory values.

Instead pull the xenopsd metadata right before updating DB.power_state in`Xapi_vm_lifecycle.force_state_reset_keep_current_operations`, eliminating the window for the race.

Closes #6451

### CODE REVIEW

**Comment by last-genius** [comment]
I've manually tested this fix and could not reproduce the issue with the xenopsd assert making a snapshot unresumable anymore.

File: ocaml/xapi/xapi_xenops.ml [hunk 1]
```diff
@@ -1714,7 +1717,8 @@ module Xenopsd_metadata = struct
         in
         delete_nolock ~__context id ;
         md
-    )
+      )
+      (fun () -> try Mutex.unlock metadata_m with Sys_error _ -> ())
```
Comment (lindig) [inline ocaml/xapi/xapi_xenops.ml:1721]: I this correct even if the lock was aquired not in this function but higher up?

**Review by lindig — APPROVED** [review]

File: ocaml/xapi/xapi_xenops.ml (hunk 1 above)
Comment (last-genius) [reply ocaml/xapi/xapi_xenops.ml:1721]: Not strictly - you're right. But there's no other users of the function and in this case we no longer need to hold the lock once `pull` is done, so it's alright

Comment (lindig) [reply ocaml/xapi/xapi_xenops.ml:1721]: You might want to leave a comment that release of the lock is ok. Altogether it would be better if we don't have to check dynamically if the lock is held already

**Comment by last-genius** [comment]
> So is the problem that this code in `Xapi_xenops.create_metadata`
> 
> ```
>   let domains =
>     (* For suspended VMs, the last_booted_record contains the "live" xenopsd state. *)
>     if vm.API.vM_power_state = `Suspended then
>       Some vm.API.vM_last_booted_record
>     else
>       None
> ```
> 
> grabs a stale `VM.last_booted_record` during the window where – in another thread that updates the DB based on an event from xenopsd – the `power_state` was already set to `Suspended` but the "real" live xenopsd state was not yet written to `VM.last_booted_record`?

Yes! Exactly

File: ocaml/xapi/xapi_xenops.ml (hunk 1 above)
Comment (last-genius) [reply ocaml/xapi/xapi_xenops.ml]: Added a comment

File: ocaml/xapi/xapi_xenops.ml [hunk 2]
```diff
@@ -1687,7 +1687,10 @@ module Xenopsd_metadata = struct
 
   (* Unregisters a VM with xenopsd, and cleans up metadata and caches *)
   let pull ~__context id =
-    with_lock metadata_m (fun () ->
+    (* Continue even if mutex is already locked one level above *)
```
Comment (Vincent-lau) [inline ocaml/xapi/xapi_xenops.ml:1690]: Is it better to use a reentrant lock here?
I think Colin has done something before to make the db lock reentrant (https://github.com/xapi-project/xen-api/commit/fae9b559cf40306a2a0a6ac2a11e10a4c7f94572), could we borrow that or use a library?

File: ocaml/xapi/xapi_xenops.ml (hunk 1 above)
Comment (last-genius) [reply ocaml/xapi/xapi_xenops.ml]: I thought so too - but didn't see any exceptions in testing. (the exception will anyhow be caught and logged by `finally`)

File: ocaml/xapi/xapi_xenops.ml [hunk 3]
```diff
@@ -1714,7 +1717,11 @@ module Xenopsd_metadata = struct
         in
         delete_nolock ~__context id ;
         md
-    )
+      )
+      (* NOTE: This function has a single user and releasing the upper-level
```
Comment (minglumlu) [inline ocaml/xapi/xapi_xenops.ml:1721]: If it has a single user always, how about making it as `pull_no_lock` so that it could solely rely on its caller to acquire the lock?

Comment (minglumlu) [reply ocaml/xapi/xapi_xenops.ml:1721]: Ah, I see. The outer lock will be acquired only when "power_state = `Suspended".

**Comment by minglumlu** [comment]
> So is the problem that this code in Xapi_xenops.create_metadata
> 
>   let domains =
>     (* For suspended VMs, the last_booted_record contains the "live" xenopsd state. *)
>     if vm.API.vM_power_state = `Suspended then
>       Some vm.API.vM_last_booted_record
>     else
>       None
> grabs a stale VM.last_booted_record during the window where – in another thread that updates the DB based on an event from xenopsd – the power_state was already set to Suspended but the "real" live xenopsd state was not yet written to VM.last_booted_record?

So the xapi event pushed the wrong metadata to the xenopsd, and then the `update_vm` pulled the wrong metadata from the xenopsd?
If so, should the xenopsd reject the pushing since the VM was in suspended state already?

File: ocaml/xapi/xapi_xenops.ml (hunk 3 above)
Comment (last-genius) [reply ocaml/xapi/xapi_xenops.ml:1721]: It won't be called unless `power_state = Suspended`, so I could just make it `pull_no_lock` indeed and leave the reentrant lock refactoring for the future if someone else starts using this function.

**Comment by last-genius** [comment]
> > So is the problem that this code in Xapi_xenops.create_metadata
> > let domains =
> > (* For suspended VMs, the last_booted_record contains the "live" xenopsd state. *)
> > if vm.API.vM_power_state = `Suspended then
> > Some vm.API.vM_last_booted_record
> > else
> > None
> > grabs a stale VM.last_booted_record during the window where – in another thread that updates the DB based on an event from xenopsd – the power_state was already set to Suspended but the "real" live xenopsd state was not yet written to VM.last_booted_record?
> 
> So the xapi event handler pushed the wrong metadata to the xenopsd, and then the `update_vm` pulled the wrong metadata from the xenopsd? If so, should the xenopsd reject the pushing since the VM was in suspended state already?

This could be another way of doing this - though I am not 100% sure we wouldn't prevent some desired behaviour this way.

File: ocaml/xapi/xapi_xenops.ml (hunk 3 above)
Comment (minglumlu) [reply ocaml/xapi/xapi_xenops.ml:1721]: Yeah, locking/unlocking twice seems a bit strange to me.

**Comment by minglumlu** [comment]
> This could be another way of doing this - though I am not 100% sure we wouldn't prevent some desired behaviour this way.

I just thought the locking scope is bigger and the lock is shared by all operations. But it may be fine as the bigger locking scope only covers the suspended case.

File: ocaml/xapi/xapi_xenops.ml [hunk 4]
```diff
@@ -2033,46 +2040,60 @@ let update_vm ~__context id =
...
+                  ( if power_state = `Suspended then
+                      let md = Xenopsd_metadata.pull ~__context id in
+                      match md.Metadata.domains with
+                      | None ->
+                          error "Suspended VM has no domain-specific metadata"
+                      | Some x ->
+                          Db.VM.set_last_booted_record ~__context ~self ~value:x ;
+                          debug "VM %s last_booted_record set to %s"
+                            (Ref.string_of self) x
+                  ) ;
```
Comment (robhoes) [inline ocaml/xapi/xapi_xenops.ml:2085]: Would it be simpler to move this block above the `Xapi_vm_lifecycle.force_state_reset_keep_current_operations` call (with a comment why)? I'm not too fond of the additional locking magic...

File: ocaml/xapi/xapi_xenops.ml [hunk 5]
```diff
@@ -2033,46 +2040,60 @@ let update_vm ~__context id =
...
-                        error "Suspended VM has no domain-specific metadata"
-                    | Some x ->
-                        Db.VM.set_last_booted_record ~__context ~self ~value:x ;
-                        debug "VM %s last_booted_record set to %s"
-                          (Ref.string_of self) x
-                ) ;
-                if power_state = `Halted then
-                  !trigger_xenapi_reregister ()
+
+                let update_allowed_operations () =
```
Comment (robhoes) [inline ocaml/xapi/xapi_xenops.ml:2044]: This function doesn't actually update allowed_operations.

**Review by robhoes — APPROVED** [review]

**Review by robhoes — CHANGES_REQUESTED** [review]
Sorry, pressed the Approve button by mistake 😅

File: ocaml/xapi/xapi_xenops.ml (hunk 4 above)
Comment (last-genius) [reply ocaml/xapi/xapi_xenops.ml:2085]: Sounds good, will test it out

Comment (last-genius) [reply ocaml/xapi/xapi_xenops.ml]: Looks good in testing, updated accordingly.

**Comment by robhoes** [comment]
>Instead pull the xenopsd metadata as soon as the power_state is updated,
shrinking the window for the race.

It's not just shrinking the window, but eliminating it: if the `VM.power_state` field in the DB is not `Suspended`, then the xenopsd metadata for the VM will not be overwritten at all. And `Xapi_vm_lifecycle.force_state_reset_keep_current_operations` is what sets `VM.power_state` in the DB.

**Review by robhoes — APPROVED** [review]
