### PR TITLE
CA-399669: Do not exit with error when IPMI readings aren't available

### LINKED ISSUE #6252: `xcp-rrdd-dcmi.service` fails when machine has no IPMI
When machine has no IPMI, we can see the systemd service fail and loop attempting to restart the service, with absolutely no detailed error:
```
Jan 27 14:03:14 xcpng83-bzkcpvhy systemd[1]: Started XCP RRD daemon IPMI DCMI power plugin.
Jan 27 14:03:14 xcpng83-bzkcpvhy systemd[1]: Starting XCP RRD daemon IPMI DCMI power plugin...
Jan 27 14:03:14 xcpng83-bzkcpvhy forkexecd: [error||0 ||forkexecd] 1160335 (/usr/bin/ipmitool -I open dcmi discover) exited with code 1
Jan 27 14:03:14 xcpng83-bzkcpvhy systemd[1]: xcp-rrdd-dcmi.service: main process exited, code=exited, status=1/FAILURE
Jan 27 14:03:14 xcpng83-bzkcpvhy systemd[1]: Unit xcp-rrdd-dcmi.service entered failed state.
Jan 27 14:03:14 xcpng83-bzkcpvhy systemd[1]: xcp-rrdd-dcmi.service failed.
Jan 27 14:03:15 xcpng83-bzkcpvhy systemd[1]: xcp-rrdd-dcmi.service holdoff time over, scheduling restart.
Jan 27 14:03:15 xcpng83-bzkcpvhy systemd[1]: Cannot add dependency job for unit lvm2-activation-early.service, ignoring: Unit is masked.
Jan 27 14:03:15 xcpng83-bzkcpvhy systemd[1]: Cannot add dependency job for unit lvm2-activation.service, ignoring: Unit is masked.
Jan 27 14:03:15 xcpng83-bzkcpvhy systemd[1]: start request repeated too quickly for xcp-rrdd-dcmi.service
Jan 27 14:03:15 xcpng83-bzkcpvhy systemd[1]: Failed to start XCP RRD daemon IPMI DCMI power plugin.
Jan 27 14:03:15 xcpng83-bzkcpvhy systemd[1]: Unit xcp-rrdd-dcmi.service entered failed state.
Jan 27 14:03:15 xcpng83-bzkcpvhy systemd[1]: xcp-rrdd-dcmi.service failed.
```

Running that command that appears in the log shows:
```
[14:15 xcpng83-bzkcpvhy ~]# /usr/bin/ipmitool -I open dcmi discover
Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
```

The service should likely stop graciously in such a condition.

Further more, the "interface" flag looks like it is not used as documented by `ipmtool --help`:
```
       -I intf        Interface to use
```

Without changing the daemon code, on a recent distro this could be used as a workaround (but looks rather kludgy):
```
ExecCondition=/usr/bin/test -d /dev/ipmi -o -d /dev/ipmidev -o -e /dev/ipmi0
```

But on the el7 base there is no such thing, and the best I could get is this, which leaves the service as "failed" but at least prevents it from useless restart attempts:
```
ExecStartPre=/usr/bin/test -d /dev/ipmi -o -d /dev/ipmidev -o -e /dev/ipmi0
```

### PR DESCRIPTION
**Pull request by psafont**
This error made toolstack restarts fail.

Because not all drivers have ipmi available, exit gracefully instead.

Also try to extract the reason from the command's output and log it. This means that now functions that use Utils.exec_cmd now red the stderr of the command as well.

Fixes #6252

### CODE REVIEW

**Review by last-genius — APPROVED** [review]
Seems fairly fragile to rely on phrasing of error messages, but it's better than what we have right now.

File: ocaml/xcp-rrdd/bin/rrdp-dcmi/rrdp_dcmi.ml [hunk 1]
```diff
@@ -27,31 +27,49 @@ let ipmitool_bin = "/usr/bin/ipmitool"
...
-      else
-        None
-    )
+    ~read_out_line ~read_err_line
 
 let get_dcmi_power_reading () =
+  let read_out_line line =
+    (* example line: '     Instantaneous power reading:                    34 Watts' *)
+    try Scanf.sscanf line " Instantaneous power reading : %f Watts" Option.some
+    with Scanf.Scan_failure _ | End_of_file -> None
```
Comment (lindig) [inline ocaml/xcp-rrdd/bin/rrdp-dcmi/rrdp_dcmi.ml:66]: Would it not be safer to catch all exceptions?

File: ocaml/xcp-rrdd/lib/plugin/utils.ml [hunk 2]
```diff
@@ -45,19 +48,25 @@ let exec_cmd (module D : Debug.DEBUG) ~cmdstring ~(f : string -> 'a option) =
...
+    let in_channel = Unix.in_channel_of_descr fd in
+    let vals = ref [] in
+    let rec loop () =
+      let line = input_line in_channel in
+      let ret = f line in
+      (match ret with None -> () | Some v -> vals := v :: !vals) ;
+      loop ()
+    in
+    (try loop () with End_of_file -> ()) ;
+    Unix.close fd ; List.rev !vals
```
Comment (lindig) [inline ocaml/xcp-rrdd/lib/plugin/utils.ml:66]: Should this not be done with `finally`? We will not reach this if we have an exception different from `End_of_file`. I also believe we have a function to iterate over a file line by line - but maybe it's not available here.

* `lines_fold` in `ocaml/libs/xapi-stdext/lib/xapi-stdext-unix/unixext.ml`

**Review by lindig — APPROVED** [review]

**Review by lindig — APPROVED** [review]

**Comment by psafont** [comment]
I've rerun the binary with the new code in exec_cmd, works as expected
